name: Mirror to GitLab

on:
  push:
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Scarica tutta la cronologia per poterla copiare

      - name: Push su GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Sostituisci "tuo-utente/tuo-repo" con il percorso reale su GitLab
          git push --mirror https://oauth2:${GITLAB_TOKEN}@gricad-gitlab.univ-grenoble-alpes.fr/bortolam/quantized-feature-in-learning-theory.git
